#spring.application.name=Pixel_perfection
server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://database-admin.database.windows.net:1433;database=Pixel_perfection;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
    username: pixelperfection-sqlserver@database-admin
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.tool.hbm2ddl: DEBUG

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

# JWT
jwt:
  base64-secret: ZNsuIEYem0dC12lgBymX2bCpRj8V2FYIJyVdwNjsCr+aZD4xVya98ZmdS9Yv5xwYjTzdQReKJDq5E76AxMebzQ==
  access-token-validity-in-seconds: 900     # 15 minutes = 900 seconds
  refresh-token-validity-in-seconds: 604800  # 7 days = 604800 seconds
# Logging
logging:
  level:
    com.example.pixel_perfection: DEBUG
    org.springframework.security:  TRACE
    org.springframework.web: DEBUG